services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cartaovacina-sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: Express
    ports:
      - "${SQL_PORT}:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q 'SELECT 1' -C"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - cartaovacina-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cartaovacina-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "${API_PORT}:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - cartaovacina-network

volumes:
  sqlserver_data:

networks:
  cartaovacina-network:
    driver: bridge
